<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AppointmentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('appointments')->insert([
            [
                'id' => 1,
                'discount' => 1,
                'registered_local' => 0,
                'accepted' => NULL,
                're_assigned' => NULL,
                'status' => 0,
                'stars' => NULL,
                'picked_date' => '2025-03-22 11:00:00',
                'note' => NULL,
                'user_id' => 13,
                'service_id' => 2,
                'package_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-03-20 22:01:29',
                'updated_at' => '2025-03-20 22:01:29',
            ],
            [
                'id' => 2,
                'discount' => 0,
                'registered_local' => 0,
                'accepted' => NULL,
                're_assigned' => NULL,
                'status' => 0,
                'stars' => NULL,
                'picked_date' => '2025-03-22 15:00:00',
                'note' => NULL,
                'user_id' => 13,
                'service_id' => NULL,
                'package_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2025-03-20 22:03:18',
                'updated_at' => '2025-03-20 22:03:18',
            ],
            [
                'id' => 3,
                'discount' => 1,
                'registered_local' => 0,
                'accepted' => NULL,
                're_assigned' => NULL,
                'status' => 0,
                'stars' => NULL,
                'picked_date' => '2025-03-25 13:00:00',
                'note' => NULL,
                'user_id' => 15,
                'service_id' => 1,
                'package_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-03-20 22:18:38',
                'updated_at' => '2025-03-20 22:18:38',
            ],
            [
                'id' => 4,
                'discount' => 0,
                'registered_local' => 0,
                'accepted' => NULL,
                're_assigned' => NULL,
                'status' => 0,
                'stars' => NULL,
                'picked_date' => '2025-03-25 17:00:00',
                'note' => NULL,
                'user_id' => 15,
                'service_id' => NULL,
                'package_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2025-03-20 22:20:10',
                'updated_at' => '2025-03-20 22:20:10',
            ],
            [
                'id' => 5,
                'discount' => 1,
                'registered_local' => 0,
                'accepted' => NULL,
                're_assigned' => NULL,
                'status' => 0,
                'stars' => NULL,
                'picked_date' => '2025-03-25 17:00:00',
                'note' => NULL,
                'user_id' => 16,
                'service_id' => 3,
                'package_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-03-20 23:54:14',
                'updated_at' => '2025-03-20 23:54:14',
            ],
            [
                'id' => 6,
                'discount' => 0,
                'registered_local' => 0,
                'accepted' => NULL,
                're_assigned' => NULL,
                'status' => 0,
                'stars' => NULL,
                'picked_date' => '2025-03-29 17:00:00',
                'note' => NULL,
                'user_id' => 16,
                'service_id' => NULL,
                'package_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2025-03-20 23:55:18',
                'updated_at' => '2025-03-20 23:55:18',
            ],
            [
                'id' => 7,
                'discount' => 1,
                'registered_local' => 0,
                'accepted' => NULL,
                're_assigned' => NULL,
                'status' => 0,
                'stars' => NULL,
                'picked_date' => '2025-03-30 13:00:00',
                'note' => NULL,
                'user_id' => 17,
                'service_id' => 1,
                'package_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-03-21 00:12:12',
                'updated_at' => '2025-03-21 00:12:12',
            ],
            [
                'id' => 8,
                'discount' => 0,
                'registered_local' => 0,
                'accepted' => NULL,
                're_assigned' => NULL,
                'status' => 0,
                'stars' => NULL,
                'picked_date' => '2025-03-30 13:00:00',
                'note' => NULL,
                'user_id' => 17,
                'service_id' => NULL,
                'package_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2025-03-21 00:13:10',
                'updated_at' => '2025-03-21 00:13:10',
            ],
            [
                'id' => 9,
                'discount' => 1,
                'registered_local' => 1,
                'accepted' => NULL,
                're_assigned' => NULL,
                'status' => 0,
                'stars' => NULL,
                'picked_date' => '2025-03-26 11:00:00',
                'note' => NULL,
                'user_id' => 3,
                'service_id' => 1,
                'package_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-03-21 17:19:35',
                'updated_at' => '2025-03-21 17:19:35',
            ],
            [
                'id' => 10,
                'discount' => 1,
                'registered_local' => 1,
                'accepted' => NULL,
                're_assigned' => NULL,
                'status' => 0,
                'stars' => NULL,
                'picked_date' => '2025-03-26 11:00:00',
                'note' => NULL,
                'user_id' => 3,
                'service_id' => 2,
                'package_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-03-21 17:19:51',
                'updated_at' => '2025-03-21 17:19:51',
            ],
            [
                'id' => 11,
                'discount' => 1,
                'registered_local' => 1,
                'accepted' => NULL,
                're_assigned' => NULL,
                'status' => 0,
                'stars' => NULL,
                'picked_date' => '2025-03-27 11:00:00',
                'note' => NULL,
                'user_id' => 3,
                'service_id' => 3,
                'package_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-03-21 17:41:39',
                'updated_at' => '2025-03-21 17:41:39',
            ],
            [
                'id' => 12,
                'discount' => 1,
                'registered_local' => 1,
                'accepted' => NULL,
                're_assigned' => NULL,
                'status' => 0,
                'stars' => NULL,
                'picked_date' => '2025-03-28 11:00:00',
                'note' => NULL,
                'user_id' => 8,
                'service_id' => 2,
                'package_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-03-21 17:41:49',
                'updated_at' => '2025-03-21 17:41:49',
            ],
            [
                'id' => 13,
                'discount' => 1,
                'registered_local' => 1,
                'accepted' => NULL,
                're_assigned' => NULL,
                'status' => 0,
                'stars' => NULL,
                'picked_date' => '2025-03-27 11:00:00',
                'note' => NULL,
                'user_id' => 5,
                'service_id' => 2,
                'package_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-03-21 18:45:53',
                'updated_at' => '2025-03-21 18:45:53',
            ],
        ]);
    }
}
