<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Admin',
                'phone' => NULL,
                'email' => 'admin@email.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Sp6F1QkNKTyvbs06Ei4vP.ZhOkdbkwuS6FQYyj89ycvp9OhyBHvmi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 1,
                'deleted_at' => NULL,
                'ref' => '000000',
                'doc' => 'V',
                'created_at' => '2025-03-20 18:36:25',
                'updated_at' => '2025-03-20 18:36:25',
            ],
            [
                'id' => 2,
                'name' => 'Admin',
                'phone' => NULL,
                'email' => 'browslashes.stefy@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$fErZ/9AB4dSq8NNk6ySpr.vh9klZ3X9GWndbXBwU98a8fYZupnOA6',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 1,
                'deleted_at' => NULL,
                'ref' => '22339147',
                'doc' => 'V',
                'created_at' => '2025-03-20 18:36:25',
                'updated_at' => '2025-03-20 18:36:25',
            ],
            [
                'id' => 3,
                'name' => 'Cliente',
                'phone' => NULL,
                'email' => 'user@email.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$05LK.NM/D5u/Q0kj3mU0Gudl2A2T.R3XH96SwyYzRCNiU7m5xKtpm',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 1,
                'deleted_at' => NULL,
                'ref' => '999999999',
                'doc' => 'V',
                'created_at' => '2025-03-20 18:36:25',
                'updated_at' => '2025-03-20 18:36:25',
            ],
            [
                'id' => 4,
                'name' => 'Cliente',
                'phone' => '04125512151',
                'email' => 'cliente@email.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$O58KvfwoULMLc2wZUEVUNul/523CH0F39VCm1q1KVyzeShVhOTBgy',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 1,
                'deleted_at' => NULL,
                'ref' => '000001',
                'doc' => 'V',
                'created_at' => '2025-03-20 18:36:26',
                'updated_at' => '2025-03-20 18:36:26',
            ],
            [
                'id' => 5,
                'name' => 'Noa Rivas Segundo',
                'phone' => '04121241212',
                'email' => 'leo59@hotmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$IugrnphiJ9LZCiJPGvk/r.3G72qCxmmKSu0EMA9PyFBZVf2Ah36BK',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 0,
                'deleted_at' => NULL,
                'ref' => '000002',
                'doc' => 'V',
                'created_at' => '2024-01-21 02:56:39',
                'updated_at' => '2025-03-20 18:36:27',
            ],
            [
                'id' => 6,
                'name' => 'Srta. Nahia Sevilla Hijo',
                'phone' => '04144564545',
                'email' => 'hector04@hispavista.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$WOZA6V/SnJ5u3QG6TUC9vO9Z7QoHEwbF/tUOQ.JCTGXzT7vZUbc96',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 0,
                'deleted_at' => NULL,
                'ref' => '000003',
                'doc' => 'V',
                'created_at' => '2024-07-02 17:04:14',
                'updated_at' => '2025-03-20 18:36:28',
            ],
            [
                'id' => 7,
                'name' => 'D. Guillem Ortega',
                'phone' => '04161231231',
                'email' => 'lflorez@baca.com.es',
                'email_verified_at' => NULL,
                'password' => '$2y$12$iWK1mxAPirjrKly0WEsRuuv2nGZgHX3JuyqXWx7xXTg2GM4.07Aju',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 0,
                'deleted_at' => NULL,
                'ref' => '000004',
                'doc' => 'V',
                'created_at' => '2024-11-30 16:26:28',
                'updated_at' => '2025-03-20 18:36:28',
            ],
            [
                'id' => 8,
                'name' => 'Fátima Tirado',
                'phone' => '04247415421',
                'email' => 'berta80@hispavista.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$.v9x.8j/4yFMw7i8nXwRaeHhAIXOXkoMOSpc/LoUeYNym42YJF3KC',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 1,
                'deleted_at' => NULL,
                'ref' => '000005',
                'doc' => 'V',
                'created_at' => '2024-12-12 19:32:17',
                'updated_at' => '2025-03-20 18:36:28',
            ],
            [
                'id' => 9,
                'name' => 'Rafael Cadena',
                'phone' => '04124567832',
                'email' => 'porras.antonio@alicea.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$dxT8bUFL0NDzBSoeOu9nduS3JHVwac2lDy.7UeaHssvUx1fEDYq42',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 0,
                'ref' => '000006',
                'doc' => 'V',
                'deleted_at' => NULL,
                'created_at' => '2024-10-03 16:47:29',
                'updated_at' => '2025-03-20 18:36:29',
            ],
            [
                'id' => 10,
                'name' => 'Stephany Villasmil',
                'phone' => NULL,
                'email' => 'empleado1@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$7B658TDSv1q58NU7fpKckutvbuR8rzbKFIA7.z2mBEBFIfvhTMn6.',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 1,
                'deleted_at' => NULL,
                'ref' => '30956447',
                'doc' => 'V',
                'created_at' => '2025-03-20 18:36:29',
                'updated_at' => '2025-03-20 18:36:29',
            ],
            [
                'id' => 11,
                'name' => 'Jose David',
                'phone' => NULL,
                'email' => 'empleado2@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$eqN6/tHcZoNo5bjQTS3GcO6VGkWB30e1MzclgA0ZPFc.mt9mEHIQK',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 1,
                'deleted_at' => NULL,
                'ref' => '27167510',
                'doc' => 'V',
                'created_at' => '2025-03-20 18:36:30',
                'updated_at' => '2025-03-20 18:36:30',
            ],
            [
                'id' => 12,
                'name' => 'Alexandra Marquez',
                'phone' => NULL,
                'email' => 'empleado3@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Ya8mGSjvSdwOEwM2JCvdmO27WDFaocBHvGvXTsfHJjoy/serQ5uom',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 1,
                'deleted_at' => NULL,
                'ref' => '26090347',
                'doc' => 'V',
                'created_at' => '2025-03-20 18:36:30',
                'updated_at' => '2025-03-20 18:36:30',
            ],
            [
                'id' => 13,
                'name' => 'Valeria',
                'phone' => '04128008000',
                'email' => 'valeria@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$19aiJI8rB1fUQSFG1qLJ0.TRP7MKDi4IT5uiIdMNT.d8O6TXIlrly',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 1,
                'ref' => '000007',
                'doc' => 'V',
                'deleted_at' => NULL,
                'created_at' => '2025-03-20 22:00:11',
                'updated_at' => '2025-03-20 22:00:11',
            ],
            [
                'id' => 14,
                'name' => 'Karla',
                'phone' => '04240000000',
                'email' => 'karla@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$fcmyWQi0ytLloMHbK8bVM.kKiSTy2N2Ur8lDyouSf2154/.oPboY6',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 1,
                'ref' => '000008',
                'doc' => 'V',
                'deleted_at' => NULL,
                'created_at' => '2025-03-20 22:10:44',
                'updated_at' => '2025-03-20 22:10:44',
            ],
            [
                'id' => 15,
                'name' => 'Katiusca',
                'phone' => '04248088080',
                'email' => 'katy@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$NP2MG7rVNZ6RPcPNARi6tOGJ8X78wX6jCVtP7Qp7NePysYxwCcoqW',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 1,
                'ref' => '000009',
                'doc' => 'V',
                'deleted_at' => NULL,
                'created_at' => '2025-03-20 22:16:56',
                'updated_at' => '2025-03-20 22:25:27',
            ],
            [
                'id' => 16,
                'name' => 'Milagro',
                'phone' => '04121111111',
                'email' => 'milagros12@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$SyNRtj3XpQbtZErH2Qlub.MEDdvqc6zxoyuLYripke0BYoCKh9QcG',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 1,
                'ref' => '000010',
                'doc' => 'V',
                'deleted_at' => NULL,
                'created_at' => '2025-03-20 23:52:14',
                'updated_at' => '2025-03-20 23:52:14',
            ],
            [
                'id' => 17,
                'name' => 'Teresa',
                'phone' => '04120333333',
                'email' => 'teresa1010@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$CDe2tELiM.xJsKE.Gx6GNupCXHJQByuRA9ScrcOA49acXojUBQk5W',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 1,
                'ref' => '000011',
                'doc' => 'V',
                'deleted_at' => NULL,
                'created_at' => '2025-03-21 00:11:04',
                'updated_at' => '2025-03-21 00:11:04',
            ],
            [
                'id' => 18,
                'name' => 'Lorena',
                'phone' => '04125121212',
                'email' => 'lorena@email.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$QDjhzj/LYf7feN7UL3tp6e2SS6d2dKqtbDSaIxIh1WTASxAf/AObK',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'active' => 1,
                'ref' => '000012',
                'doc' => 'V',
                'deleted_at' => NULL,
                'created_at' => '2025-03-21 17:53:15',
                'updated_at' => '2025-03-21 17:53:15',
            ],
        ]);
    }
}
